"""empty message

Revision ID: 207990557251
Revises: c61abe5eca07
Create Date: 2021-03-14 21:22:26.134066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207990557251'
down_revision = 'c61abe5eca07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seasons_id', sa.Integer(), nullable=False),
    sa.Column('watching_datetime', sa.DateTime(), nullable=True),
    sa.Column('watched_time', sa.DateTime(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seasons_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'seasons_id')
    )
    op.drop_table('user_seasons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_seasons',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('seasons_id', sa.INTEGER(), nullable=False),
    sa.Column('watching_datetime', sa.DATETIME(), nullable=True),
    sa.Column('watched_time', sa.DATETIME(), nullable=True),
    sa.Column('episode', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['seasons_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'seasons_id')
    )
    op.drop_table('user_series')
    # ### end Alembic commands ###
