"""empty message

Revision ID: 7098b8533cbf
Revises: 27b94ea9b611
Create Date: 2021-03-13 02:09:28.784574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7098b8533cbf'
down_revision = '27b94ea9b611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('FWlink', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('IMDBlink', sa.String(length=100), nullable=True))
    op.add_column('series', sa.Column('FWlink', sa.String(length=100), nullable=True))
    op.add_column('series', sa.Column('IMDBlink', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'IMDBlink')
    op.drop_column('series', 'FWlink')
    op.drop_column('movies', 'IMDBlink')
    op.drop_column('movies', 'FWlink')
    # ### end Alembic commands ###
