"""empty message

Revision ID: cbc6a8cf23bd
Revises: ceb7e1bed7c2
Create Date: 2021-03-14 01:33:05.881733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc6a8cf23bd'
down_revision = 'ceb7e1bed7c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_movie', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_movie', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_seasons', sa.Column('seasons_id', sa.Integer(), nullable=False))
    op.alter_column('user_seasons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'user_seasons', type_='foreignkey')
    op.create_foreign_key(None, 'user_seasons', 'seasons', ['seasons_id'], ['id'])
    op.drop_column('user_seasons', 'season_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_seasons', sa.Column('season_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_seasons', type_='foreignkey')
    op.create_foreign_key(None, 'user_seasons', 'seasons', ['season_id'], ['id'])
    op.alter_column('user_seasons', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_seasons', 'seasons_id')
    op.alter_column('user_movie', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_movie', 'movie_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
